### ISSUE TITLE
public_ip and vnet_id are currently mutually exclusive. 

### ISSUE THREAD

**Issue by robwafle** [test-kitchen/kitchen-azurerm#113] opened 2019-08-20 21:53 UTC
# Version:

0.14.9

# Environment:

N/A

# Scenario:

Azure supports a public IP when a machine is joined to a vnet.  We need the public IP for winrm orchestration -- so test kitchen can continue to run chef -- and the VM to be on the subnet so it can access IP addresses on the subnet.  We'd like to avoid having to be connected to the same vnet using a vpn client.

# Steps to Reproduce:

Just use kitchen.yml example 4 - deploy VM to existing virtual network/subnet (use for ExpressRoute/VPN scenarios) and set public_ip flag to true.  Check the portal, and the machine is not added to the vnet.

# Expected Result:

I'm expecting the machine to be added to the vnet but also have a public ip.

# Actual Result:

The machine is NOT added to the vnet but does have a public ip.

**Comment by stuartpreston** [comment] 2019-11-29 09:24
Hi @robwafle - thanks for taking the time to send in this report. I was unable to reproduce this. Using the following configuration my machine is both added to the vnet/subnet I specify and has a public IP, which is saved to the state file for further use.

Configuration in kitchen.yml: 
```yml
platforms:
  - name: ubuntu-on-vnet
    driver:
      image_urn: Canonical:UbuntuServer:16.04-LTS:latest
      vnet_id: /subscriptions/43706c4e-b31d-425e-b5f5-e64e6bf63ac4/resourceGroups/sp-infrastructure/providers/Microsoft.Network/virtualNetworks/sp-vnet-northeurope
      subnet_id: default
      public_ip: true
    transport:
      name: ssh
      ssh_key: ~/.ssh/id_kitchen-azurerm
```


```
I, [2019-11-29T09:15:51.163230 #9180]  INFO -- default-ubuntu-on-vnet: -----> Creating <default-ubuntu-on-vnet>...
I, [2019-11-29T09:15:51.169104 #9180]  INFO -- default-ubuntu-on-vnet: Creating Resource Group: kitchen-default-ubuntu-on-vnet-20191129T091551
I, [2019-11-29T09:15:52.884276 #9180]  INFO -- default-ubuntu-on-vnet: Creating deployment: deploy-fc2e218487d55c22
I, [2019-11-29T09:15:52.884705 #9180]  INFO -- default-ubuntu-on-vnet: Using custom vnet: /subscriptions/43706c4e-b31d-425e-b5f5-e64e6bf63ac4/resourceGroups/sp-infrastructure/providers/Microsoft.Network/virtualNetworks/sp-vnet-northeurope
I, [2019-11-29T09:15:52.890783 #9180]  INFO -- default-ubuntu-on-vnet: Adding public key from C:/Users/spreston/.ssh/id_kitchen-azurerm.pub to the deployment.
I, [2019-11-29T09:16:04.578219 #9180]  INFO -- default-ubuntu-on-vnet: Resource Microsoft.Compute/virtualMachines 'vm' provisioning status is Running
I, [2019-11-29T09:16:15.019460 #9180]  INFO -- default-ubuntu-on-vnet: Resource Microsoft.Compute/virtualMachines 'vm' provisioning status is Running
I, [2019-11-29T09:16:25.327197 #9180]  INFO -- default-ubuntu-on-vnet: Resource Microsoft.Compute/virtualMachines 'vm' provisioning status is Running
I, [2019-11-29T09:16:35.635187 #9180]  INFO -- default-ubuntu-on-vnet: Resource Microsoft.Compute/virtualMachines 'vm' provisioning status is Running
I, [2019-11-29T09:16:46.065073 #9180]  INFO -- default-ubuntu-on-vnet: Resource Microsoft.Compute/virtualMachines 'vm' provisioning status is Running
I, [2019-11-29T09:16:56.363639 #9180]  INFO -- default-ubuntu-on-vnet: Resource Microsoft.Compute/virtualMachines 'vm' provisioning status is Running
I, [2019-11-29T09:17:06.518446 #9180]  INFO -- default-ubuntu-on-vnet: Resource Template deployment reached end state of 'Succeeded'.
I, [2019-11-29T09:17:07.023684 #9180]  INFO -- default-ubuntu-on-vnet: IP Address is: 52.169.249.163 [kitchen-fc2e218487d55c22.northeurope.cloudapp.azure.com]
I, [2019-11-29T09:17:07.029306 #9180]  INFO -- default-ubuntu-on-vnet: Finished creating <default-ubuntu-on-vnet> (1m15.86s).
```

Portal view of VM showing nic is attached to vnet and public ip is assigned too:
![image](https://user-images.githubusercontent.com/6384654/69858208-715d9780-1289-11ea-8828-b219932948f0.png)

For now I'm going to mark this as "can't repro" in an attempt to keep the issue list low - if you have more information about this feel free to reopen the issue!

**Closed by stuartpreston** 2019-11-29 09:24 UTC
Labels: maintainer unable to repro
