### ISSUE TITLE
Adding user assigned identities no longer works in 0.14.9

### ISSUE THREAD

**Issue by zanecodes** [test-kitchen/kitchen-azurerm#117] opened 2019-11-01 19:07 UTC
As of `kitchen-azurerm` 0.14.9, attempting to add a user assigned identity using the `user_assigned_identities` config option results in the following error:

```
-----> Starting Kitchen (v2.3.3)
-----> Creating <azonly-windows)...
       Creating Resource Group: kitchen-azonly-windows-20191101T151822
       Creating deployment: deploy-3df06c328c2ae4d4
       Adding WinRM configuration to provisioning profile.
       Resource Microsoft.Network/publicIPAddresses 'publicip' provisioning status is Running
       Resource Microsoft.Network/virtualNetworks 'vnet' provisioning status is Running
       Resource Template deployment reached end state of 'Failed'.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [{"error"=>{"code"=>"InvalidParameter", "message"=>"ResourceIdentity property identityIds is deprecated. The userAssignedIdentities property should be used instead.", "target"=>"resourceIdentity.identityIds"}}] on azonly-windows
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

This appears to be due to [this change,](https://github.com/test-kitchen/kitchen-azurerm/commit/98956f532fc4767142c3dbecd071c1389cba97dd#diff-f54020f0d902169c779f2e6df5a1b617R285) at least according to [the Azure documentation.](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/qs-configure-template-windows-vm#assign-a-user-assigned-managed-identity-to-an-azure-vm)

Implementing a fix may end up being a bit annoying due to the [new property's structure.](https://github.com/MicrosoftDocs/azure-docs/issues/24687)

**Comment by stuartpreston** [comment] 2019-11-11 18:42
Ugh. Thanks for the report.

**Comment by nhudacin** [comment] 2020-01-23 16:26
I just hit this same issue. Following as I might be able to help out.

**Comment by nhudacin** [comment] 2020-01-27 16:41
Ok... So I confirmed that if we draw the line and say that `kitchen-azurerm` will only support 1 user-assigned identity, then the code change is actually pretty easy and I'm just able ready to put a PR in for that. I can't imagine why anyone would want to assign multiple identities to a VM, I don't even know how that would work or why MSFT supports it. 

I like this approach because it doesn't change any of the interfaces for any of us who use this property so our .kitchen.yml files will start working again without having to change them all. Basically handling the type change behind the scenes with something like this: 

```ruby
userAssignedIdentities: config[:user_assigned_identities][0].to_s,
```

If we need to support multiple user identities then I'll need to add some template code in the erb files to handle it.

**Comment by StylusEaterChef** [comment] 2020-08-27 18:27
@zanecodes It looks like this was addressed with your code. Mind closing out the issue?

**Closed** 2020-08-27 18:59 UTC
Labels: bug, help wanted
